version: "2"
exclude_patterns:
    - 'app/*.php'
    - 'var/**'
    - 'web/*.php'
    - '*.min.js'
    - 'app/AppCache.php'
    - 'app/AppKernel.php'
    - 'app/autoload.php'
    - 'var/SymfonyRequirements.php'
    - 'web/app_dev.php'
    - 'web/app.php'
    - 'web/config.php'