---
engines:
    phpcs:
        enabled: true
        php_version: 7.1
        exclude_paths:
            - 'app/**'
            - 'var/**'
            - 'web/*.php'
            - 'app/AppCache.php'
            - 'app/AppKernel.php'
            - 'app/autoload.php'
            - 'var/SymfonyRequirements.php'
            - 'web/app_dev.php'
            - 'web/app.php'
            - 'web/config.php'
    coverage:
        enabled: true
    exclude_paths:
        - 'app/*.php'
        - 'var/**'
        - 'web/*.php'
        - '*.min.js'
        - 'app/AppCache.php'
        - 'app/AppKernel.php'
        - 'app/autoload.php'
        - 'var/SymfonyRequirements.php'
        - 'web/app_dev.php'
        - 'web/app.php'
        - 'web/config.php'
