language: php
php:
  - '7.1'

services:
  - mysql

test:
  adapter: mysql2
  database: symfony
  username: travis
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE symfony;'

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load -n
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - php vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT